### ISSUE TITLE
Oauth2 error: redirect URI not configured correctly

### ISSUE THREAD

**Issue by MrIonic** [FamilySearch/integration-data-copy#10]
I made progress.  I installed a web server and now the login-button takes me to:
https://ident.familysearch.org/cis-web/oauth2/v3/authorization?response_type=code&client_id=a02j00000098ve6AAA&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F

However, I now get: 
Oauth2 error: redirect URI not configured correctly

I didn't give up, opting to setup a dynamic DNS entry to use a real hostname but still get the same error.
Suggestions?

Do I need to configure my local copy of the source with my personal FamilySearch developer credentials?

**Comment by justincy** [comment]
Yes, you need to configure the app to work with your own credentials. You can obtain a client ID (app key) and configure a redirect URI at https://grms.force.com/Developer/FSDev_CommunitiesCustomLogin?startURL=%2FFSDev_MyDevHomePage
