### ISSUE TITLE
Doesnt copy

### ISSUE THREAD

**Issue by CristianCardosoA** [FamilySearch/integration-data-copy#8]
Doesn't copy anything !!!!!!!

![captura de pantalla 2016-11-02 a la s 13 17 56](https://cloud.githubusercontent.com/assets/18292956/19943844/d45c8936-a0fe-11e6-9600-6943a939169e.png)

**Comment by justincy** [comment]
Green means it successfully copied. I also checked and those relationships exist. What's wrong?

**Comment by misbach** [comment]
@CristianCardosoA Maybe you confused those IDs with Person IDs? Here is an example API call you can make to see one of those relationships you created.
`https://integration.familysearch.org/platform/tree/couple-relationships/MJL2-PNP`

**Comment by CristianCardosoA** [comment]
If I sign in to my sandbox account -> tree. I got a error message.
![Uploading Screenshot_2016-11-02-14-34-50.png…]()

**Comment by CristianCardosoA** [comment]
If a sign in to my sandbox account > TREE or my profile. I got a error message
![screenshot_2016-11-02-14-34-50](https://cloud.githubusercontent.com/assets/18292956/19946682/f3d35498-a112-11e6-8d7c-8012eecebba5.png)

**Comment by misbach** [comment]
@CristianCardosoA What error are you seeing? That red text in your screenshot isn't an error, it's just informing you that you are using our sandbox reference instead of production.

**Comment by CristianCardosoA** [comment]
This is the error.

![img-20161102-wa0019](https://cloud.githubusercontent.com/assets/18292956/19947948/5a21903e-a118-11e6-804c-49c2deeccab6.jpg)

**Comment by justincy** [comment]
Try using integration.familysearch.org instead of sandbox

**Comment by CristianCardosoA** [comment]
Thanks to both @justincy and @misbach
